sonar.projectKey=Valentin222259_Licenta
sonar.organization=valentin222259
sonar.sources=src,backend
sonar.exclusions=backend/db/**,backend/jobs/**,**/node_modules/**,**/dist/**,**/*.test.js,**/*.spec.js
sonar.coverage.exclusions=backend/db/**,backend/jobs/**
